version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Restoring .NET Core dependencies..."
      - dotnet restore AiBuilderServerDotnet.sln
      - echo "Building the .NET Core application..."
      - dotnet build AiBuilderServerDotnet.sln
      - echo "Publishing the .NET Core application..."
      - dotnet publish AiBuilderServerDotnet/AiBuilderServerDotnet.csproj -c Release -o ./publish
artifacts:
  files:
    - '**/*'
  base-directory: ./publish
